# Generated by Django 6.1 on 2026-08-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_studentskill"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("technologies", models.CharField(blank=True, max_length=300)),
                ("project_type", models.CharField(blank=True, max_length=100)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="core.profile",
                    ),
                ),
            ],
        ),
    ]
