# Generated by Django 6.1 on 2026-08-27 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_studentproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_name", models.CharField(max_length=150)),
                ("issuing_organization", models.CharField(max_length=150)),
                ("issue_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="core.profile",
                    ),
                ),
            ],
        ),
    ]
