# Generated by Django 6.1 on 2026-08-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_studentcertification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("HACKATHON", "Hackathon"),
                            ("INTERVIEW", "Interview"),
                            ("PRESENTATION", "Presentation"),
                            ("COMPETITION", "Competition"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "required_skills",
                    models.CharField(
                        help_text="Enter skills separated by commas", max_length=500
                    ),
                ),
                (
                    "minimum_skill_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        default="BEGINNER",
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
